# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f56afc1ca834649a3022d5b7fd2035d65acf3085338f0744e2d57ec2e9d13541b77fde62bbaa1005eb80d438945e337f0536483ee85e280da6d7376a8872b0b2

test:
  secret_key_base: d84649d2c6a6011bddf0bd32f1f854b2e17b7880bdeb4f2fa334d44e1004ab28cedd7574af2c8653f35a28fbb75dfba98e53080e791a73a555793eb5faa580bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
